### ISSUE TITLE
Electron App

### ISSUE THREAD

**Issue by bcomnes** [workshopper/javascripting#100]
This would be even cooler if it had an electron app to go along with it. :sunglasses: Ps add me :+1:

**Comment by sethvincent** [comment]
:tada:

**Comment by bcomnes** [comment]
:beers:

**Comment by SomeoneWeird** [comment]
Do you just mean have a terminal bundled up in a electron app?

**Comment by bcomnes** [comment]
Whatever makes sense.  Since javascriping is just JavaScript, it might open up the workshop to more people if we have a CLI-less option that works in the browser/desktop app.

**Comment by SomeoneWeird** [comment]
If somebody doesn't have access to a terminal, that will make it extremely hard for them to learn to dev, but anyway - yeah, that could be cool.

**Comment by bcomnes** [comment]
it's definitely an experient, but it could serve as a blueprint for other adventures that would be useful knowing before or even outside the cli.

**Comment by bcomnes** [comment]
I'll try to flesh this out more during the upcoming nodeschool.

**Comment by bcomnes** [comment]
the git-it adventure already does its content mostly as a web page, and now is getting an electron app:

https://github.com/jlord/git-it-electron

Get-dat is also a good example of an adventure that strays away from the command line and is browser only.  

http://maxogden.github.io/get-dat/

Still thinking on the best way to adapt this to electron.
