### ISSUE TITLE
Using a story to teach the 'why' of JavaScript

### ISSUE THREAD

**Issue by gwmccull** [workshopper/javascripting#108]
Hi,

I helped mentor a NodeSchool a few weeks ago in Reno, NV.  After the workshops, the mentors got together to compare notes and we noticed that a lot of people had the same questions and problems.  One of the them was the for loop exercise that already has an issue on it.  A lot of students had trouble understanding "why" they would use programming and the exercises only described the "how".

We came up with the idea of re-building the exercises but incorporating a running story to help give the "why" and also attempting to clean up some of the recurring misunderstandings that we saw.

Would you be interested in seeing this as a fork of this project?  Or would it be better if I created a new project?

Thanks!

**Comment by SomeoneWeird** [comment]
Hi! I think it would be pretty awesome to see some 'story' exercises too, I've found the same thing (why vs how). You could probably find a way to include them in javascripting, maybe each exercise can have 2 parts, a why, where you you explain different situations you might need to do something in, and a how, which describes how to do it (current ones). Final say is up to @sethvincent though, and yourself, if you want to include them :)

**Comment by bcomnes** [comment]
Hi @gwmccull I've actually been working on an article covering the why and the where of learning node+javascript.  Its still an early draft, but the basics of why are already covered:

https://github.com/bcomnes/node-learnbook#what-is-javascript

Feedback, PRs and critique welcome!

I think turning in the why into a nodeschool adventure would also be a totally awesome project.

**Comment by gwmccull** [comment]
@SomeoneWeird Thanks for the feedback.  The idea was to primarily re-write the explanation of each exercise and the success/fail message that appears after the exercise is tested.  For the most part, the exercises seem good.  We had talked about the possibility of adding some more exercises because, in some cases, the jumps in difficulty were pretty big between exercises.  But that would be out in the future.

@bcomnes Thanks for sharing your draft article.  It looks like a great list of resources.  When I said people didn't understand the 'why', I meant they didn't understand why someone would be interested in programming at all.  It looks like you discuss, 'why JavaScript' but I don't see any explanation of 'why programming'. I'd like to keep the explanation with the exercises also.  I'll try to look into the NodeSchool adventure.  I've heard of that but I haven't experienced one.

Thanks for the feedback everyone.

**Comment by bcomnes** [comment]
Ahh I see.  :+1: to that idea!

**Comment by itzsaga** [comment]
2+ years later I'm closing this. Feel free to open a new Issue if people are still interested and we can see about doing it.
