### ISSUE TITLE
installing

### ISSUE THREAD

**Issue by ddeng360** [workshopper/javascripting#116]
hi, i'm new but it's not installing for some reason. I have node installed but when I type in javascripting after following the instructions, I get "-bash: javascripting: command not found". Thanks for the help!

**Comment by naltun** [comment]
Type in `node --version` and `npm --version`, and make sure both are up-to-date versions. 
Currently, the latest version of Node.js is v0.12.7.

**Comment by ddeng360** [comment]
they are up to date... i think I messed up the pathing is there anyway to check?

**Comment by SomeoneWeird** [comment]
Did you run `npm install -g javascripting`?

**Comment by calvinsettachatgul** [comment]
I had to modify my PATH variable in Mac OSX
after i ran
sudo npm install -g javascripting
The output was
/Users/username/.node/bin/javascripting -> /Users/username/.node/lib/node_modules/javascripting/bin/javascripting
/Users/username/.node/lib

In ~/.bash_profile 
I added the following line
export PATH="/Users/username/.node/lib/node_modules/javascripting/bin/:$PATH"

Then after restarting bash I was able to run 
javascripting

**Comment by gugonzar** [comment]
Hi, when I run this command "npm install -g javascripting" it starts executing but never ends. It stays showing the "\" progress character and don't finish. I'm using Win7 and node.js v4.5.0 and npm 2.15.9

I tried reinstalling node, but nothings happens.

Thanks for your help.

**Comment by calvinsettachatgul** [comment]
Did you try running node -v to test the installation?
or npm -v?
Here is something I found about installing node on windows 
http://blog.teamtreehouse.com/install-node-js-npm-windows
It does mention you have to restart your computer.

**Comment by martinheidegger** [comment]
@gugonzar  I posted an issue on NPM: https://github.com/npm/npm/issues/13722

**Comment by itzsaga** [comment]
Looks like this got resolved.
