### ISSUE TITLE
Looping Through Arrays troubles

### ISSUE THREAD

**Issue by michaelgrilo** [workshopper/javascripting#127]
Even with the _For Loop_ section pulled up, I was not able to find my own solution to the _Looping Through Arrays_ challenge. It wasn't clear to me what I should put for the variable and the condition, as well as how I should increment. 

I didn't immediately pick up on the hint that I had to define the variable `i` in order for it to be used. I also thought something like `i++` only worked on numerical values. I didn't understand how to use it on the string values of the `pets` array. 

Once I reviewed the posted solution, I realized that an arbitrarily named counter variable is what is being incremented, which is represented here by the variable `i`. This value increases every time the loop repeats. As long as the numerical value of `i` is less than the number of positions in the `pets` array, every entry in the array is assigned to be the same value with an s added to the end of it. 

I think we could phrase the `Looping Through Arrays` challenge in a way in which would have helped me come to these realizations without needing to pull up both the _For Loop_ section and the solution. This challenge took much longer to understand than any of the other ones.

**Comment by ledsun** [comment]
I think this issue has been improved somewhat in #268. Please try the new version and reopen it if you still have trouble.
