### ISSUE TITLE
Error on Windows with Git Bash

### ISSUE THREAD

**Issue by finnp** [workshopper/javascripting#136]
![img_1368](https://cloud.githubusercontent.com/assets/841788/9990971/36113dd2-6066-11e5-8eba-c65f79cf57c0.JPG)

At the last workshop one of the attendees got an error when starting `javascripting`. I tried to find the issue (which was painful due to the current structure of some modules).  It seems to me that in `simple-terminal-menu` this line returns `null`:

``` js
  if (!process.stdin.isTTY)
    return null
```

That would mean that there's something wrong with Node though. Maybe someone else has another idea.

**Comment by ccoenen** [comment]
in git bash, this happens to me:

```$ javascripting

 # Please start this in a tty-compatible terminal program.

....
```

So, at least it's not as broken as it used to. I'd reckon that someone starting javascript has exactly *zero* clue what to do about it (and what constitudes tty, tty-compatible or terminal), so the message could be better.

**Comment by ccoenen** [comment]
but other than that, javascripting runs fine on windows, as long as you stay in cmd.exe or something like [cmder](http://cmder.net/).

**Comment by itzsaga** [comment]
Closing this old issue.
