### ISSUE TITLE
Official solutions not provided after passing verification

### ISSUE THREAD

**Issue by TylerMoeller** [workshopper/javascripting#145]
Node 4.2.1, Windows 7:

Official solutions aren't provided after running, for example: `javascripting verify program.js`. Wanted to give a heads up in case this is not a known issue at this time.

Here's an example of the output:

``` md
# PASS
Your solution to ROUNDING NUMBERS passed!

Here's the official solution in case you want to compare notes:

───────────────────────────────────────────────────────────────

# THAT NUMBER IS ROUNDED

 Yep, you just rounded the number 1.5 to 2. Good job.

 In the next challenge we will turn a number into a string.

 Run javascripting in the console to choose the next challenge.

───────────────────────────────────────────────────────────────
```

**Comment by MaximeArnstamm** [comment]
Same here : node 4.2.1, OSX

**Comment by wachr** [comment]
I'm seeing the same thing. Has anyone looked into this?

**Comment by SomeoneWeird** [comment]
Seems to be an issue with the new `workshopper-adventure`.

cc @martinheidegger

**Comment by martinheidegger** [comment]
Will look at it tonighy

**Comment by martinheidegger** [comment]
Did look at it, will take a little longer, scheduling issues. Sorry

**Comment by Charlotteis** [comment]
Hi there! I am getting the same issues.

Mac OSX El Capitan, node v4.2.1, npm v2.14.7

**Comment by aneely** [comment]
Have run into the same issue days before hosting a new Nodeschool chapter workshop. Testing running this in Cloud9 for handling people who won't have Node installed on their laptops.

**Comment by lisavogtsf** [comment]
For students or teachers curious about the official solutions, they are all available in the [solutions folder in the javascripting repo](https://github.com/sethvincent/javascripting/tree/master/solutions). Each unit has a folder and in each folder is an index.js file with the solutions. 

I know I hadn't though to look for the solutions on github while I was running javascripting in the terminal, so I might double-check a couple of answers to see the official solution.

**Comment by KLVTZ** [comment]
Until then, could we simply overwrite the output message by having a custom `i18n/en.json` file?

**Comment by jmpp** [comment]
The problem is relevant to the `workshopper-adventure` dependency.

I've submitted a PR for this : https://github.com/workshopper/workshopper-adventure/pull/95

Hope that helps.

**Comment by jmpp** [comment]
PR submitted : https://github.com/workshopper/javascripting/pull/208
