### ISSUE TITLE
for-loop verify is expecting 45 instead of 10

### ISSUE THREAD

**Issue by selfup** [workshopper/javascripting#150]
#### Really dig this!

However, there seems to be a bug.

The for-loop exercise indicates that the limit variable should equal _10_.

Then when a user runs verify, it expects **45** instead of _10_.

The user then has to change the limit variable o 45 to pass the validation.

If this is by design, my apologies.

Thanks!

**Comment by SomeoneWeird** [comment]
I'm on my phone at the moment, but I'm 80% sure this is the exercise and that limit should always be 10. You need to loop 10 times and increment another variable by the loop index. (1+2+3+4+5+6+7+8+9 = 45)

**Comment by selfup** [comment]
This makes sense!

If you check the translations though, you see that they set the variable to be 45 as well. 

The Spanish one for example says so.

Thanks for clarifying!

**Comment by selfup** [comment]
I closed the PR so that the issue could be the main focus. 

Thanks!

**Comment by KLVTZ** [comment]
I think it was simply a misread on my part. When I saw `total += i` I saw it as the number `1` instead of the iterator. Made the same mistake.

**Comment by selfup** [comment]
Yup same!

No worries though :)

**Comment by ccoenen** [comment]
I'm proposing to close the issue.

It's not an actual problem of the code. If at all, one could lobby for changing `i` to something more distinct - but that's unusual as a counting variable. I'd leave it as it is and close this.
