### ISSUE TITLE
Some text invisible on Windows

### ISSUE THREAD

**Issue by pnorman** [workshopper/javascripting#153]
Some text is invisible in Windows when using PowerShell. Here is an example from array filtering

![image](https://cloud.githubusercontent.com/assets/1190866/11663104/2b31fab2-9d8f-11e5-81d5-6fe2c68719ce.png)

**Comment by jansteh** [comment]
Hello seems like I have the same problem.

**Comment by peterjacobson** [comment]
![image](https://cloud.githubusercontent.com/assets/6021319/11669156/103c907e-9e60-11e5-9da9-dd7944af3746.png)

same on ubuntu

**Comment by jansteh** [comment]
in win its realy invisible, it stays hidden even if I change the collor of
backgroung in powershell (or cmd). i found workaround to see the text: i
copy it from powershell (using mouse right key - quick edit in options) and
paste it in notepad, in notepad i see all.

**Comment by sethvincent** [comment]
Could y'all try the latest version and see if this is improved for you? 

Reinstall with npm:

```
npm i -g javascripting
```

**Comment by pnorman** [comment]
![image](https://cloud.githubusercontent.com/assets/1190866/12970799/259d0592-d048-11e5-9797-43f56e65e12d.png)

Everything except for the bright blue is readable. I looked at some other exercises, and it's only blue that I have a problem with.

In the traditional command prompt
![image](https://cloud.githubusercontent.com/assets/1190866/12970859/a94b33f0-d048-11e5-91ac-ae4fd62ba492.png)
 I find the blue hard to read there too.

**Comment by iboldurev** [comment]
Such a problem in the iterm2 color solarized Dark theme

![2017-08-04 8 40 23](https://user-images.githubusercontent.com/17103170/28955611-9577b32e-78f0-11e7-9a4d-b943312280a8.png)

![2017-08-04 8 40 41](https://user-images.githubusercontent.com/17103170/28955621-9d7b8c3a-78f0-11e7-9a04-7cb4a879fb10.png)

**Comment by lqh21** [comment]
大家好，我也在mac上遇到过这个问题，当时是使用了solarized的一套主题，然后换一套就发现能显示了。有遇到iTerm显示不全这个问题的可以试试换一套主题。
