### ISSUE TITLE
Takes 2 attempts to progress to the next exercise after completing the last one

### ISSUE THREAD

**Issue by iokiwi** [workshopper/javascripting#154]
After completing an exercise and running `javascripting` to select the next exercise, the workshop stays on the current exercise instead of moving to the next one I select. Repeating this process successfully moves the workshop on to the next exercise.

**Comment by latagore** [comment]
I'm not able to reproduce this on v2.6.1. 

If I understand correctly, the steps to do this are:
1. Start `javascripting` for the first time.
2. Select the first exercise.
3. Complete the first challenge and verify it with `javascripting verify introduction.js`.
4. Run `javascripting` again.
5. Select the second exercise. Note that the current exercise does not change.

For step 5, it does seem to change to the next exercise.

**Comment by itzsaga** [comment]
I, as well, cannot reproduce this based on the info @iokiwi provided on v2.6.1.
