### ISSUE TITLE
Some text not visible in solarized dark theme

### ISSUE THREAD

**Issue by ps-aux** [workshopper/javascripting#157]
![image](https://cloud.githubusercontent.com/assets/4789301/12529631/cd4d32f0-c1be-11e5-81fe-1f4c58b157c4.png)

In solarized dark theme certain text areas invisible. Maybe it is problem of the theme but this is rather annoying and the theme is quite popular. Possible workaround  is with `--no-colors`.

**Comment by miklb** [comment]
+1

**Comment by martinheidegger** [comment]
Note: I reworked the color palette on workshopper-adventure recently to be better readable (particularily on windows). Maybe javascripting needs an updated workshopper-adventure?

**Comment by miklb** [comment]
Not sure. Attended a nodeschool event in Tampa this evening and wasn't able to read the steps because my terminal uses the Solarized dark theme. Sure I could have switched themes, but didn't feel like fiddling with my terminal. I appreciate the free and open resources, just a heads up.

**Comment by sethvincent** [comment]
Could y'all try the latest version and see if this is improved for you?

Reinstall with npm:

```
npm i -g javascripting
```

**Comment by ondrejmo** [comment]
I've the same issue and I'm running the latest version, with --no-colors option is everything fine.

**Comment by rickheere** [comment]
@sethvincent installing the newest version indeed worked for me (Ubuntu). I think this is not longer an issue.

**Comment by claudiopro** [comment]
This is a real usability problem. I for instance find the yellow text written by [webpack](https://github.com/webpack/webpack) unreadable on a white terminal background - *yes, I like white terminal background* 😄 . Web accessibility has made huge progress, but CLI still has to catch up. True that the user can pick a different theme, but it's a barrier to entry and a hassle.

**Comment by SomeoneWeird** [comment]
I'm not sure if we can cater to every theme out there, there's always going to be something that conflicts with the styling of a cli program

**Comment by martinheidegger** [comment]
@ps-aux This is a bug of the solarized color scheme, it would be awesome if you report it! @SomeoneWeird I think it might be fixed in new versions of Workshopper, would you mind to update and redeploy it?

**Comment by SomeoneWeird** [comment]
Oh? Ok, I'll try get around to it tonight.

**Comment by esayler** [comment]
## Quick iTerm2 Fix

![screenshot 2016-08-23 18 38 07](https://cloud.githubusercontent.com/assets/5581134/17912412/61f7464e-6961-11e6-8b85-7c7c0083a229.png)

1. Open **iTerm2** -> **Preferences**
2. After selecting the **Profiles** tab, click **Colors**. 
2. On the right-side of the pane, under **ANSI Colors**, select first box in the **Bright** column (the **Black** row)
3. from the modal's dropdown, select **HSB with Brightness Slider**.
4. Drag the slider to the right to make the color brighter.

Should fix the problem without having to adjust the **minimum contrast** setting. 

You can revert to the default _Solarized Dark_ color scheme by selecting it from the **Color Presets.**. dropdown. 

### Before: 
![screenshot 2016-08-23 18 47 05](https://cloud.githubusercontent.com/assets/5581134/17912495/00a90a48-6962-11e6-9cbf-af0f98c1925d.png)

### After:
![screenshot 2016-08-23 18 44 53](https://cloud.githubusercontent.com/assets/5581134/17912466/c4eae3dc-6961-11e6-9f88-a5e62aa88732.png)

**Comment by itzsaga** [comment]
Appears to be fixed.
