### ISSUE TITLE
Irrelevant message after completing all the challenges

### ISSUE THREAD

**Issue by arun1595** [workshopper/javascripting#172]
After submitting the solution of the last challenge, we get the following output

```
# PASS Your solution to SCOPE passed!  
Here's the official solution in case you want to compare notes:  
───────────────────────────────────────────────────────────────
#EXCELLENT!  
You got it! The second function has the scope we were looking for.  
Run javascripting in the console to choose the next challenge.  
─────────────────────────────────────────────────────────────── 
You've finished all the challenges! Hooray! 
```

Once all the challenges are done, there's no use of the message asking us to run **javascripting** in the console to choose the next challenge. Of course, there's no challenge after the last one.

I think we should remove the line _"Run javascripting in the console to choose the next challenge."_ when the user solves the last challenge.

**Comment by claudiopro** [comment]
Kind of, I'd rather rephrase the invite to re-run the challenges to try and write better, more efficient solutions.

**Comment by arun1595** [comment]
I am not sure if that would work because once #145 is resolved, learners would be able to see the solutions which would be the efficient.
And I regarding efficiency, since the challenges are beginner-friendly, almost every solution is efficient.

**Comment by mdmcginn** [comment]
Could we suggest another workshopper? Is there a Javascript Level 2? Or maybe npm install -g functional-javascript-workshop

**Comment by arun1595** [comment]
@martinheidegger I like your idea to direct the learner to an intermediate-level workshopper.
We can display something along the lines of
> You've finished all the challenges! Hooray!  Now, checkout **Functional Javascript** Workshop
```
npm install -g functional-javascript-workshop
```

**Comment by claudiopro** [comment]
Hmm @arun1595 this would create an implicit dependency between workshops that would be tricky to manage (peer dependencies? optional dependencies? custom package.json field?)

**Comment by SomeoneWeird** [comment]
@claudiopro I'm not sure how that really creates a dependency, we don't have to run anything for the user, just tell them where they may wish to head next.

**Comment by claudiopro** [comment]
@SomeoneWeird well, even the assumption of the existence of a specific workshop is a dependency.

**Comment by SomeoneWeird** [comment]
You can't unpublish stuff from npm now, so we don't have to worry about that.
