### ISSUE TITLE
npm WARN deprecated workshopper-adventure@4.7.1

### ISSUE THREAD

**Issue by srdong** [workshopper/javascripting#180]
when I use '   npm install -g javascripting'
it told me that   'npm WARN deprecated workshopper-adventure@4.7.1: Accidental major release published as patch. Please use 5.0.0
'
how can I solve it!help me!its my first time to do it.

**Comment by sethvincent** [comment]
This is now fixed in version 2.6.1.

If you run `npm install -g javascripting` again you shouldn't see that warning message.
