### ISSUE TITLE
verify parameter is ignored

### ISSUE THREAD

**Issue by orboan** [workshopper/javascripting#181]
Hello, 
please take a look at:
nodeschool/discussions#1898

and let me know if anyone can help or have any clues.
Thank you so much.

**Comment by sethvincent** [comment]
I haven't been able to reproduce it yet, but I just published v2.6.1.

It contains a bug fix (for the workshopper-adventure error message you mention in nodeschool/discussions#1898), though I'm not sure if it'll address this issue.

If you could try it out and let me know if the issue remains, I'd appreciate it.

**Comment by itzsaga** [comment]
Closing this, if this is still an issue let us know @orboan.
