### ISSUE TITLE
Object properties (Exercise 16 of 19) Content Issue.

### ISSUE THREAD

**Issue by maRanaylaK** [workshopper/javascripting#185]
//Content from command prompt

__________________________________________________________________________________________________________________

 # JAVASCRIPTING

 ## OBJECT PROPERTIES (Exercise 16 of 19)

  You can access and manipulate object properties -- the keys and values
  that an object contains -- using a method very similar to arrays.

  Here's an example using square brackets:

     var example = {
       pizza: 'yummy'                                            //NO QUOTES TO PIZZA HERE
     };

     console.log(example['pizza']);

  The above code will print the string 'yummy' to the terminal.

  Alternately, you can use dot notation to get identical results:

     example.pizza;                                               //NO QUOTES TO PIZZA

     example['pizza'];

  The two lines of code above will both return yummy.

 ## The challenge:

  Create a file named object-properties.js.

  In that file, define a variable named food like this:

     var food = {
       types: 'only pizza'                                              //NO QUOTES TO types
     };

  Use console.log() to print the types property of the food object to the
  terminal.

  Check to see if your program is correct by running this command:

     javascripting verify object-properties.js

_______________________________________________________________________________________________________________

//Content End

In the content shown the key values that are taken(pizza,types) have not been quoted making it seem like a something else other than a STRING so in order for the values to be generated the keys should be placed in quotes.

I have tried it normally thinking this is how node might work but did not work and then tried adding quotes and it worked. 

Thank You.

**Comment by AnshulMalik** [comment]
@maRanaylaK 

What I understood from this issue is, 

You are trying to print the value of an object's key using `console.log(food[types])`
But it generates an error, and then you tried `console.log(food['types'])`, which worked fine.

Let me know if I got it right.

**Comment by maRanaylaK** [comment]
Yes so without the quotes it might be considered a variable or something else so hence did not work.

**Comment by AnshulMalik** [comment]
Yes, If you write is without quotes, like `console.log(food[types])`, types is considered as a variable and it's value is substituted in case the variable is initialised.

So the content looks right to me.

**Comment by maRanaylaK** [comment]
But there is no variable types declared anywhere not even pizza right because those are keys in the dictionary and they should be values(as in constants) and types is not a string variable to substitute its value but it is the value itself(if the quotes is added).
