### ISSUE TITLE
about how to use in windows ! windows用户的操作方式需要转变！！！

### ISSUE THREAD

**Issue by pythoncat1024** [workshopper/javascripting#195]
if you are a windows user ,after `npm install --global javascripting` .maybe you will do 

> Open your terminal and run the following command:
> javascripting

but, unfortunately. you will received an error in your cmd ,like this "javascripting is not an internal or external command, nor is it a program that can run" . so what should a windows user do?

**Now , I will share the right way do in windows**
if your os is windows 10 
   1.  open your _powershell_ .
   2. `cd`your current path to the `javascripting`**,then input `.\javascripting`**
   3. you can choose one item ,then press enter key.
   4. enjoy your trainning.

ps: I am a chinese, I am very poor in english. so,maybe what I say you do not understand. Now,I will write all steps in chinese.

如果你当前使用的是windows环境，那么按照`Run the workshop`上面的步骤是不可行的。因为在执行了`npm install --global javascripting`，并且按照完成之后，在命令行里面执行`javascripting`命令会提示**'javascripting' 不是内部或外部命令，也不是可运行的程序
或批处理文件。**

正确的做法是：
使用powershell，然后，找到javascripting安装后的位置：比如我的是：E:\npm_packages\npm_g。然后，把powershell的当前路径也cd 到这里来。然后执行`'\javascripting`命令就可以打开了。后续的操作，所有需要执行`javascripting`命令的地方全部换成`.\javascripting`即可。比如校验命令，应该替换成：`.\javascripting verify E:\javascriptWorkFloder\scope.js`。里面路径切换成你自己的即可。

**Comment by CodinCat** [comment]
> javascripting is not an internal or external command, nor is it a program that can run

This is because you didn't setup environment variable (PATH) for npm correctly. For example it should be something like `C:\Users\<username>\AppData\Roaming\npm`

Simply add this to your PATH and it will work.

**Comment by pythoncat1024** [comment]
No. what you say is not correct. the first time I received the error 

> javascripting is not an internal or external command, nor is it a program that can run

I just go to search the solution about this. then, I find one answer like you said.then I add `C:\Users\<username>\AppData\Roaming\npm` to my path. but it dose not work. then I try to use _powershell_.It works. 

Of course, I know ,I have to add C:\Users\<username>\AppData\Roaming\npm` to my path.but it is not the complete steps. after do this ,also should use _powershell_ . 

Anyway, thanks for your answer. because it's also helpful for other windows user and me.

**Comment by CodinCat** [comment]
It does work if you setup everything properly. I just tried on my Windows. Simply run `npm install -g javascripting`  then `javascripting` in `cmd` and it works. There is no need to use powershell or anything. I didn't even restart my  `cmd`.

**Comment by AnshulMalik** [comment]
I see, @pythoncat1024 was trying to help people using windows. But I think creating an issue might not help since it's not an issue, it's place is somewhere is docs.

**Comment by pythoncat1024** [comment]
Thank you. may be I made some mistakes when I install _Node_ or _npm_ ,or some error occured when the environment is configured.

oh.maybe this problem only appeared in my windows. sorry for what I say to you and this issue.

but I also hope this issue exist in the future, becasue  others maybe encounter this problem. @AnshulMalik

**Comment by itzsaga** [comment]
I agree with @AnshulMalik that this is not a true issue with the code but an issue with the npm setup.

**Comment by pythoncat1024** [comment]
ok ok ok . it is not a issue with this code .

**Comment by itzsaga** [comment]
I'm allergic to cats so I'm closing this issue. :smile_cat:
