### ISSUE TITLE
Solution checker just checks output

### ISSUE THREAD

**Issue by AnshulMalik** [workshopper/javascripting#196]
With out current implementation, we check the solution by comparing the output of solution program with expected, it has many issues, since same output can be generated in lot of ways.

We'd want to have some rigid solution checker which can check

- Variable is declared or not
- Any variable's value at any line (Deal with scopes)
- Function is declared or not
- Function's parameters

[Here](https://github.com/workshopper/javascripting/blob/master/problems/for-loop/problem.md) we want to observe the value of for loop's local variable `i` over iterations.
  

We can have discussion on how we can implement this and land a basic version.

**Comment by itzsaga** [comment]
Jasmine?

**Comment by AnshulMalik** [comment]
We can use it as a candidate :+1: , but I don't know whether jasmine provide this feature to evaluate values of variables.
May be you can do some digging into jasmine to see whether it can do what we want ?

**Comment by itzsaga** [comment]
Will do. 👍

**Comment by itzsaga** [comment]
@bsommardahl showed me how to solve our testing problem today in Jest. See https://gist.github.com/bsommardahl/da8251512a0a72facca9c12aea4bdb7b
I think this is a solid option for consideration.

**Comment by ledsun** [comment]
Because the discussion has stopped, I closed this issue. If you find a new idea, reopen this.
