### ISSUE TITLE
Inconsistency in using single-quotes vs double-quotes for strings

### ISSUE THREAD

**Issue by SkullTech** [workshopper/javascripting#197]
In _exercise 3_, there's an instruction like this -
```
Try to stay consistent. In this workshop we'll only use single quotation marks.
```
But in _exercise 19_, there's a sample code given to be copy pasted which goes like this -
``` 
console.log("a: "+a+", b: "+b+", c: "+c);
```

This inconsistency should be fixed.

**Comment by AnshulMalik** [comment]
I think you are talking about [this](https://github.com/workshopper/javascripting/blob/master/solutions/scope/index.js#L8)

Nice catch, we'll fix it soon :)

**Comment by itzsaga** [comment]
@SkullTech took care of this in #198.
