### ISSUE TITLE
the directions to run the intro program are not explicit

### ISSUE THREAD

**Issue by alpha-dog** [workshopper/javascripting#201]
i've CAPS LOCKED and !!!!!exclaimed!!!!! what i'm talking about in the code quote below. after completing the intro exercise, it prints all of this: 

```
# YOU DID IT!

 Anything between the parentheses of console.log() are printed to the
 terminal.

 So this:

    console.log('hello');

 prints hello to the terminal.

 Currently we are printing a string of characters ### to the terminal: hello.

 In the next challenge we focus on learning about variables.

 Run javascripting in the console to choose the next challenge.

 You have 18 challenges left.

 Type 'javascripting' to show the menu.

─────────────────────────────────────────────────────────────────────────────
 Need help? View the README for this workshop:
 (http://github.com/sethvincent/javascripting)

─────────────────────────────────────────────────────────────────────────────

  » To print these instructions again, run: javascripting print
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  » TO EXECUTE YOUR PROGRAM IN A TEST ENVIRONMENT, RUN: JAVASCRIPTING RUN
      PROGRAM.JS
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  » To verify your program, run: javascripting verify program.js
  » For help run: javascripting help
```

when it prints out in the integrated vs code terminal on my mac, the 'program.js' portion of the above referenced code is on a different line (as depicted), and is a different color (not depicted, but it's the color of the instructional text). on my regular bash terminal it looks like one line of code and is all the same font/color, so that's nice. 

my grievance is that 'program.js', in the above example, should be more explicitly defined as an abstract 'exampleProgramThatIsNotTheRealNameOfTheProgramYouAreTryingToRun.js' example. this also applies to the line of code below what i've referenced (i.e. `To verify your program, run: javascripting verify program.js`)the difference between conventional naming and required naming is continually frustrating, especially for beginners.   

otherwise, i really like node school so far. keep up the good work

**Comment by itzsaga** [comment]
Hey @alpha-dog,
While we could be more explicit with `program.js` I think we cover this at the end of the INTRODUCTION lesson:

> By the way, throughout this tutorial, you can give the file you work with any name you like, so if you want to use something like `catsAreAwesome.js` file for every exercise, you can do that. Just make sure to run:
>
> ```bash
> javascripting verify catsAreAwesome.js
> ```

**Comment by itzsaga** [comment]
Closing this. If you feel strongly about this Pull Requests to improve things are always welcome :-)
