### ISSUE TITLE
Modern JavaScript!?

### ISSUE THREAD

**Issue by huberv** [workshopper/javascripting#212]
Hi all,
I'd like to modernize the problems and solution to use let and const instead of only var.

Would that match your expectation about the lessons?

Is there any guideline about what the "baseline" JavaScript version is for all of the nodeschool workshops (like "if a JS feature is green on https://caniuse.com, then it is ok/should be used in the lessons")?

**Comment by itzsaga** [comment]
Hey @huberv,

I think ES6 is definitely a solid thing we could introduce. Desktop browsers compatibility is looking solid: https://kangax.github.io/compat-table/es6/ and worldwide IE usage is <4% http://gs.statcounter.com/ I would just say to throw an IE note in somewhere.

Looking forward to what you come up with.

**Comment by laoshaw** [comment]
indeed this should be upgraded to at least ES6 for nowadays' usage.

**Comment by claudiopro** [comment]
@huberv agree with @itzsaga and @laoshaw, I'd say everything that is in the finished proposals is game https://github.com/tc39/proposals/blob/master/finished-proposals.md

**Comment by itzsaga** [comment]
Keeping track of the update in #229
