### ISSUE TITLE
 the specifications are not shown in the problems.

### ISSUE THREAD

**Issue by DarkCode01** [workshopper/javascripting#217]
At the moment of entering the section or chapter of the variables in the exercise, it shows it to me like this:

## The challenge:
    Create a file named.
    In that file declare a named variable.
    Make the variable equal to the value.
    Then use to print the variable to the console.
    Check to see if your program is correct by running this command:

**Comment by martinheidegger** [comment]
Can you reinstall javascripting and see if that issue is still there?
