### ISSUE TITLE
Stray [object Object] output in javascripting run 

### ISSUE THREAD

**Issue by robbiethegeek** [workshopper/javascripting#218]
Testing under: 
node --version
v8.9.4

javascripting: 
"version": "2.6.1"

On a Mac: 10.13.3 (17D47)
---------
When you run on the first problem.
javascripting run introduction.js
hello
  [object Object]

The introduction.js file contains: 
console.log('hello');

When running purely with Node:
node introduction.js
hello

**Comment by ledsun** [comment]
Use the `verify` command instead of the `run`.

Like next:
```
javascripting verify introduction.js
```

**Comment by robbiethegeek** [comment]
So yes this does not happen when you verify. But every time you use run you get this stray output and that is very confusing to people who are new as an old school organizer I was trying to figure out when this was happening and how to codify it so I don't think the answer is just use verify since this happens anytime you are using javascripting run to troubleshoot your code.

**Comment by AnshulMalik** [comment]
If you would like to fix it, you can find the code which runs on `run` https://github.com/workshopper/workshopper-adventure/blob/master/index.js#L264

And for verify https://github.com/workshopper/workshopper-adventure/blob/master/index.js#L260

**Comment by robbiethegeek** [comment]
I may at some point take a look at the code, but so far on this thread I have been told not to run a basic command that is part of what makes workshopper modules tick, and told the fix the problem I have reported.  If this was someone that was new to the community and this was their first interaction with an open source community I think they would likely be put off and assume the only people that should be here are those that can fix all the issues they report.

Just a heads up as to how this has gone in the last 6 days.

**Comment by AnshulMalik** [comment]
Sorry for that @robbiethegeek , Since people generally come here hunting for bugs as well so I thought you might be willing as well. 

But anyway, nice bug, we'll definitely fix this in upcoming releases :)

Thanks for reporting.

**Comment by itzsaga** [comment]
@AnshulMalik is this still open?

**Comment by AnshulMalik** [comment]
Yep, still open.

**Comment by ledsun** [comment]
This issue was fixed with https://github.com/workshopper/javascripting/commit/c403678db1e1fb15f7b438b4b5b0e976568a5500 .

```
~ javascripting run index.js
run is not required for this exercise.
```
