### ISSUE TITLE
Translation for Brazilian Portuguese language it is not using new spelling reform

### ISSUE THREAD

**Issue by aceiro** [workshopper/javascripting#219]
Some codes is not using new standard for Portuguese Language Rules defined around 1990 - 2009. 

> (...)Because there are differences between the Portuguese spoken in Portugal and the Portuguese spoken in Brazil, the reform has led to the creation of new spellings that once were the same in both countries.

[Speeling reform](https://en.wikipedia.org/wiki/Spelling_reform)

Can I contribute for this repository ? Is it active yeat ?

**Comment by itzsaga** [comment]
@aceiro you can definitely contribute! See this doc for how to implement localization: https://github.com/workshopper/javascripting/blob/master/LOCALIZING.md
It'd be great to have both the pt-PT and pt-BR languages implemented.

**Comment by AryanJ-NYC** [comment]
@itzsaga Thoughts on adding the `hacktoberfest` label to this issue?

**Comment by itzsaga** [comment]
@AryanJ-NYC anything that might help to get it done :-)
