### ISSUE TITLE
(Kind of weird) line wrap in Exercise 1 (Introduction) in cmd

### ISSUE THREAD

**Issue by lkreimann** [workshopper/javascripting#225]
Hi all, I noticed a weird line wrap that might be confusing for newbies - at least it kinda confused me because (at first) I didn't look at the next line to see if there's more to the command.

![grafik](https://user-images.githubusercontent.com/22977266/43864082-f41fc09c-9b5e-11e8-9b9a-d6f7e6b69f3a.png)
You can see this here (captured in Cmder), I was able to recreate that behavior in cmd (on Windows) too.

Maybe there's a fix to display the whole command in one line :)

**Comment by itzsaga** [comment]
This just has to do with the width of your terminal window (Cmder and cmd) in your case. If you make the window wider this will resolve itself.
