### ISSUE TITLE
error on ubuntu 16 at start javascripting

### ISSUE THREAD

**Issue by Akaronte** [workshopper/javascripting#226]
i started 
# javascripting
/usr/local/lib/node_modules/javascripting/node_modules/joi/lib/index.js:38
    return schema._init(...args);
                        ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/javascripting/node_modules/explicit/lib/validate/index.js:3:11)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

# uname -a
Linux ubuntu16 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

# node -v
v4.2.6

# npm view javascripting

{ name: 'javascripting',
  description: 'Learn JavaScript by adventuring around in the terminal.',
  'dist-tags': { latest: '2.6.1' },
  versions:
   [ '1.0.0',
     '1.0.1',
     '1.1.0',
     '1.1.1',
     '1.1.2',
     '1.1.3',
     '1.2.0',
     '1.3.0',
     '1.4.0',
     '1.5.0',
     '1.6.0',
     '1.7.0',
     '1.8.0',
     '1.9.0',
     '1.9.1',
     '1.10.0',
     '1.10.1',
     '1.10.2',
     '1.10.3',
     '1.11.0',
     '1.11.1',
     '1.12.0',
     '2.0.0',
     '2.0.1',
     '2.0.2',
     '2.0.3',
     '2.1.0',
     '2.2.0',
     '2.2.1',
     '2.3.0',
     '2.4.0',
     '2.4.1',
     '2.5.0',
     '2.6.0',
     '2.6.1' ],
  maintainers:
   [ 'julianduque <julianduquej@gmail.com>',
     'leichtgewicht <martin.heidegger@gmail.com>',
     'sethvincent <sethvincent@gmail.com>',
     'someoneweird <adam@boxxen.org>',
     'tdd <tdd@tddsworld.com>' ],
  time:
   { modified: '2018-03-19T05:26:37.543Z',
     created: '2014-09-29T23:39:48.451Z',
     '1.0.0': '2014-09-29T23:39:48.451Z',
     '1.0.1': '2014-09-29T23:59:19.313Z',
     '1.1.0': '2014-09-30T03:36:31.160Z',
     '1.1.1': '2014-10-06T22:17:28.676Z',
     '1.1.2': '2014-10-08T19:25:17.003Z',
     '1.1.3': '2014-10-13T17:50:45.871Z',
     '1.2.0': '2014-10-20T04:57:18.962Z',
     '1.3.0': '2014-10-23T10:17:02.186Z',
     '1.4.0': '2014-10-27T19:00:20.854Z',
     '1.5.0': '2014-11-01T05:55:21.193Z',
     '1.6.0': '2014-11-03T20:58:04.269Z',
     '1.7.0': '2014-11-12T20:28:22.482Z',
     '1.8.0': '2014-12-01T20:11:39.730Z',
     '1.9.0': '2014-12-18T18:21:37.619Z',
     '1.9.1': '2015-01-05T20:35:57.055Z',
     '1.10.0': '2015-01-17T19:01:03.101Z',
     '1.10.1': '2015-01-19T17:27:29.520Z',
     '1.10.2': '2015-01-28T21:51:37.488Z',
     '1.10.3': '2015-02-01T19:09:58.401Z',
     '1.11.0': '2015-02-20T19:05:53.381Z',
     '1.11.1': '2015-03-16T23:32:20.983Z',
     '1.12.0': '2015-03-30T17:38:33.315Z',
     '2.0.0': '2015-05-18T17:27:51.004Z',
     '2.0.1': '2015-05-18T18:31:43.565Z',
     '2.0.2': '2015-05-23T19:54:00.637Z',
     '2.0.3': '2015-05-25T17:13:25.100Z',
     '2.1.0': '2015-09-04T02:15:34.600Z',
     '2.2.0': '2015-10-23T07:19:07.223Z',
     '2.2.1': '2015-10-23T23:19:39.222Z',
     '2.3.0': '2015-11-21T02:27:00.499Z',
     '2.4.0': '2015-12-14T18:49:37.467Z',
     '2.4.1': '2016-02-11T05:16:03.381Z',
     '2.5.0': '2016-03-15T04:52:07.884Z',
     '2.6.0': '2016-04-16T23:23:00.220Z',
     '2.6.1': '2016-10-11T21:02:00.578Z' },
  homepage: 'https://github.com/sethvincent/javascripting#readme',
  repository: { url: 'git+https://github.com/sethvincent/javascripting.git' },
  author: 'sethvincent',
  bugs: { url: 'https://github.com/sethvincent/javascripting/issues' },
  readmeFilename: 'README.md',
  users:
   { substack: true,
     alanshaw: true,
     mykhael: true,
     pnevares: true,
     nickleefly: true,
     tylerm: true,
     mattqs: true,
     coder_clod: true,
     michalhodur: true,
     takonyc: true },
  license: 'MIT',
  version: '2.6.1',
  bin: { javascripting: './bin/javascripting' },
  main: './index.js',
  preferGlobal: true,
  dependencies:
   { colors: '^1.0.3',
     promise: '^7.1.1',
     diff: '^1.2.1',
     'workshopper-adventure': '^5.0.0' },
  gitHead: 'b080365f9627e8876dfe63f2ed53e89ef735eb70',
  scripts: {},
  dist:
   { shasum: 'bdfd7f4bd0dd0e87bddea622149a8c6e922ba475',
     tarball: 'https://registry.npmjs.org/javascripting/-/javascripting-2.6.1.tgz' },
  directories: {} }

**Comment by AnshulMalik** [comment]
Try upgrading node to 8.x or 6.x

**Comment by Akaronte** [comment]
# node -v
v10.10.0
# npm -v
6.4.1
 Now is running ok
