### ISSUE TITLE
Update exercises to use const and let instead of var 

### ISSUE THREAD

**Issue by itzsaga** [workshopper/javascripting#229]
We are gradually migrating from `var` to `const`. The exercises still contain code that uses `var`. We should change `var` usage to `const` or `let` as applicable.

PRs welcome :)
Please create one PR per exercise and a change should be applied to the translations as well. 

- [x] variables
- [x] strings
- [x] string-length
- [x] revising-strings
- [x] numbers
- [x] rounding-numbers
- [x] number-to-string
- [x] if-statement
- [x] for-loop
- [x] arrays
- [x] array-filtering
- [x] accessing-array-values
- [x] looping-through-arrays
- [x] objects
- [x] object-properties
- [x] functions
- [x] function-arguments
- [x] scope

**NOTE:**
- **Please consider the `problem.md` and it's translation files as well**
- Create PR against `es6` branch

**Comment by itzsaga** [comment]
accessing-array-values in #228

**Comment by SomeoneWeird** [comment]
What's the rationale behind one PR per exercise?

**Comment by AnshulMalik** [comment]
It's easier to review and contains changes specific to a single problem. We can also revert in future if something is not right. @SomeoneWeird

**Comment by AnshulMalik** [comment]
Ohh sorry about that, you should unwatch the repository in case you don't want to be notified for all notifications.

**Comment by Violet-XiaoWeiHuang** [comment]
Hello Seth, 
I would like to contribute to this project, and I am new to this project. 
I wonder whether I can update any file in your repository, like this https://github.com/workshopper/javascripting/blob/master/solutions/arrays/index.js
@itzsaga

**Comment by lupomontero** [comment]
Hi there,

Just wondering what's the state of this issue? How is this related to #214? Is there anything I could do to help getting this done?

**Comment by itzsaga** [comment]
@lupomontero based on the OP checklist we're still missing one.

**Comment by ledsun** [comment]
congratulation that all exercise were fixed 🎉
