### ISSUE TITLE
Publish a new version?

### ISSUE THREAD

**Issue by ledsun** [workshopper/javascripting#269]
javscripting has 83 commits since version 2.6.1.
Almost 80 contributors sent PRs.
I want to release new version of the javascripting.

Who can publish new version to the npm repository?

@julianduque
@tdd 
@martinheidegger
@SomeoneWeird
@sethvincent

**Comment by sethvincent** [comment]
@ledsun I added you as a maintainer on npm. Feel free to release a new version or let me know what the version number should be.

**Comment by ledsun** [comment]
Thank you very much. A new version has been released.
