### ISSUE TITLE
Variables Exercise 2 - Command Failed Help

### ISSUE THREAD

**Issue by drystar** [workshopper/javascripting#280]
I am trying to complete Exercise 2 - Variables but struggling with an error

Here's screenshots of the terminal error/ VSC

Is something missing maybe?

Thank you

<img width="431" alt="Screenshot 2019-09-16 at 1 31 29 PM" src="https://user-images.githubusercontent.com/52010925/64991428-b24b3000-d886-11e9-8318-0363b9cf3354.png">

<img width="934" alt="Screenshot 2019-09-16 at 1 28 28 PM" src="https://user-images.githubusercontent.com/52010925/64991443-b9723e00-d886-11e9-88f0-4b9a5cf5c64e.png">

**Comment by feross** [comment]
You already declared the variable `example` by writing `let example`, so you are not allowed to declare another variable with the same name again, which is what the line `const example = ...` is doing. You can just remove the first line `let example` to fix this.
