### ISSUE TITLE
Move challenges todo from README to an issue

### ISSUE THREAD

**Issue by ccarruitero** [workshopper/javascripting#282]
I think would be more organized keep challenges todo in an issue.

Aside, we could use the issue to request and discuss new challenges for todo.

**Comment by ledsun** [comment]
As an experiment, I made #283 related to "FUNCTION RETURN VALUES".

I think it's better to discuss new challenges in this way.
What do you think?

**Comment by ccarruitero** [comment]
@ledsun, it's a great idea. That way is even better.

**Comment by itzsaga** [comment]
Awesome @ledsun, I agree with @ccarruitero. Happy to see updated versions released in the wild now.

**Comment by ccarruitero** [comment]
I just opened #284 to add @ledsun 's proposal like a github template. Take a look when you have a chance.

**Comment by ledsun** [comment]
@sethvincent I merged #284, but I don't have permission to set the issue template.

**Comment by sethvincent** [comment]
@ledsun you should have access now.

**Comment by ledsun** [comment]
I set the issue template. Please let me know if you notice something.
