### ISSUE TITLE
syntax highlighting in terminal

### ISSUE THREAD

**Issue by maxogden** [workshopper/javascripting#3]
hey this module rules so far!

I use the default white terminal style on macOS and it looks like this:

![screen shot 2014-10-13 at 8 16 47 pm](https://cloud.githubusercontent.com/assets/39759/4613190/deeafc7e-52d2-11e4-8801-bc41355fe013.png)

I hooked up http://npmjs.org/ansimd but it required me sending this PR https://github.com/stephenmathieson/node-ansimd/pull/1

I think it would be best to disable syntax highlighting by default, but im not sure if the cli-md module can do that

if you like ansimd more I can send a PR once the upstream one lands

**Comment by martinheidegger** [comment]
Now switched to workshopper it should be the same problem for all depending workshoppers

**Comment by hicksca** [comment]
I use Solarized in iTerm2 with the [colorator][1] gem (for syntax highlighting when print to the terminal) and I seem to be having the same issue. 

![screen shot 2015-08-12 at 4 49 31 pm][2]

Switch to another theme in my terminal and this seemed to have helped.

![screen shot 2015-08-12 at 4 59 23 pm][3]

Will file and issue with @altercation seems to be an issue within individual themes. I have tested a few dark and light and for the most part it seems to be hit and miss. 


[1]: https://rubygems.org/gems/colorator
[2]: https://cloud.githubusercontent.com/assets/3722310/9237695/2cd193a2-4112-11e5-8a10-25d14779c6c0.png
[3]: https://cloud.githubusercontent.com/assets/3722310/9237894/ab0f0604-4113-11e5-849e-89f21709a43b.png

**Comment by wachr** [comment]
Based on [this comment](https://github.com/nodeschool/discussions/issues/1358#issuecomment-153990874) there's a '--no-color' argument to the javascripting command.

**Comment by whiteadam** [comment]
@wachr thanks for the no-color option, really helps us colorblind people :)

**Comment by itzsaga** [comment]
Over a year since this came up and the `--no-color` argument is a fix. Closing this.
