### ISSUE TITLE
EEXIST: file already exists error

### ISSUE THREAD

**Issue by sroopsai** [workshopper/javascripting#301]
**Error**
`EEXIST: file already exists, mkdir '/home/support/.config/workshopper'`

**To Reproduce**
1. Type the command `javascripting` again after first time.

**Expected behavior**
1. We should get this error `EEXIST: file already exists, mkdir '/home/support/.config/workshopper'` even if we use `javascripting print` to print the instructions again. 

**Execution environment (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Node Version: v8.9.4

**Comment by Nerdastic** [comment]
Running into the same issue... have you found a solution yet?

**Comment by Nerdastic** [comment]
Okay - with help from some other people I got it sorted out: 
"try using this “nvm install 12.18.2” to install the new node and then try running the javascripting command again, it should work."

if that does not work, then rm -r the .config file that contains the javascripting directory, and install javascripting again using the: 
npm install -g javascripting

Now try running javascripting again. 

Sorry about the poorly formatted answer- I am a noob lol. But this worked for me.

**Comment by sroopsai** [comment]
:tada: It's working. Thank you :smile:

**Comment by FunkyRobot73** [comment]
Thank you very much...  got it working.
