### ISSUE TITLE
Introduction - syntax error when running console.log('hello');

### ISSUE THREAD

**Issue by Brett-A-Clark** [workshopper/javascripting#317]
When I try running console.log('hello'); I receive the following error message:

vagrant [vagrant]> mkdir javascripting
vagrant [vagrant]> cd javascripting
vagrant [javascripting]> touch introduction.js
vagrant [javascripting]> console.log('hello');
-bash: syntax error near unexpected token `'hello''

**Comment by itzsaga** [comment]
@Brett-A-Clark I think you may have missed this in the instructions:

> Open the file in your favorite editor, and add this text:
> 
> ```js
> console.log('hello')
> ```

**Comment by Brett-A-Clark** [comment]
Thank you. However I don't understand the next step when I get here. Screenshot attached.
![Screen Shot 2021-06-16 at 6 27 14 AM](https://user-images.githubusercontent.com/81992490/122227932-35d6ee00-ce6c-11eb-9fc0-928802f50e86.png)

**Comment by itzsaga** [comment]
@Brett-A-Clark perfect. Now following along with the instructions:

> Save the file, then check to see if your program is correct by running this command:
> 
> ```bash
> javascripting verify introduction.js
> ```

Save the file with `CTRL + X`. You'll be asked if you want to save the changes. Type `Y` to confirm. Then back in your command line where you were originally execute `javascripting verify introduction.js`. What happens after those steps are taken?

**Comment by itzsaga** [comment]
@Brett-A-Clark okay. Make sure to go through the Install steps listed [here](https://github.com/workshopper/javascripting#install-nodejs) to ensure Node & the `javascripting` package are installed correctly.

**Comment by Brett-A-Clark** [comment]
I was able to resolve issue. Thank you for your help, it's difficult to follow instructions as GIF changes images quickly
