### ISSUE TITLE
Array Filtering Syntax Error

### ISSUE THREAD

**Issue by Brett-A-Clark** [workshopper/javascripting#319]
Below is the code I'm using which is similar to example. Feel like Im missing something obvious. Please help. Thank you.

const numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
const filtered = numbers.filter(function evenNumbers (number) {
return (number % 2 === 0)
}) console.log(filtered);

**Comment by itzsaga** [comment]
@Brett-A-Clark have you searched the error to try and understand what it means? If so, what do you think it means? What have you tried and not had success with? What were the errors you received each time and did you search and work to understand what each error you have received means?

Please try and keep from creating issues unless you believe there is something wrong with `javascripting` that needs to be fixed. General help requests to complete problems is not what issues are intended to be used for.
