### ISSUE TITLE
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by ansaar14** [workshopper/javascripting#324]
I am getting this error and do not know how to troubleshoot it

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

 and now when I tried to verify my program, nothing is loading

**Comment by ledsun** [comment]
Can you run any other commands?
For example:

```
javascripting
```

or

```
javascripting print
```

or

```
javascripting help
```

**Comment by ledsun** [comment]
Close this issue once. Reopen this if there is new information.
