### ISSUE TITLE
error when running 'javascripting'

### ISSUE THREAD

**Issue by natiteg** [workshopper/javascripting#353]
p.stdin.setRawMode(true)
            ^

TypeError: p.stdin.setRawMode is not a function

**Comment by EhsaanFayazShah** [comment]
Hello natiteg.
I simply consider reinstalling Node.js and npm. (https://nodejs.org/en)
and after that run this command in your terminal: npm install -g javascripting.
and at last run "javascripting" command.
Hope this could help you out if not then It seems like there might be an issue with the code within the workshop itself..

**Comment by ledsun** [comment]
Close. 
If you have additional information, feel free to reopen.
