### ISSUE TITLE
For loops are confusing

### ISSUE THREAD

**Issue by stephanieosan** [workshopper/javascripting#54]
Writing javascript for this first time last night with this tutorial, but the tutorial's description of for loops stumped me! 

I had to get my dev-friends to explain how they work. :pizza:

**Comment by sethvincent** [comment]
Hi! 

We revised the text for that challenge somewhat recently. If you installed javascripting a while ago you might want to run `npm install -g javascripting` again to get the latest version (right now the latest is v1.10.2). 

Or if you do have the latest version it would be cool to hear which sections are most confusing. 

Here's the current text for that challenge: https://github.com/sethvincent/javascripting/blob/master/problems/for-loop/problem.md

**Comment by SomeoneWeird** [comment]
Can I ask what exactly you found confusing? (I understand it might be hard/impossible to explain) It would help us figure out what needs to be rewritten :)

**Comment by stephanieosan** [comment]
Yes! I do have the latest version. 

Based on your description:
![screen shot 2015-02-04 at 1 23 13 pm]
(https://cloud.githubusercontent.com/assets/6433178/6046526/fef8e6e6-ac70-11e4-96b1-2ee3fe078c18.png)

I didn't grasp that the stuff in the parentheses controlled how many times the for loop ran, where as the stuff in the curly brackets is the action that's being performed. I also didn't get that those three pieces in the parentheses were always required to make a for loop go. 

If what I just said doesn't make sense, maybe it's an indication that I *still* don't understand. :fearful:

**Comment by sethvincent** [comment]
Got it. That definitely makes sense, and is super helpful! Thanks.

**Comment by stephanieosan** [comment]
Excellent!

**Comment by jpdamon** [comment]
@sethvincent I updated the wording based on the feedback, to help clarify what the parts of the for loop mean. Let me know what you think.
