### ISSUE TITLE
translations

### ISSUE THREAD

**Issue by sethvincent** [workshopper/javascripting#76]
javascripting now has i18n support thanks to @martinheidegger!

@a0viedo, @NgaNguyenDuy: we could potentially merge the translations you've been working on into this module to make things simpler. You can look at the additions made in the latest commits to see how the japanese translation works. let me know what you think!

**Comment by NgaNguyenDuy** [comment]
Wow. Yup. I will check your commit and push commit as soon as possible. Thx for reminding. :-)

**Comment by manuelitox** [comment]
Hello,

I would help with the translations to Spanish. This it's possible?

**Comment by SomeoneWeird** [comment]
@manuelitox Absolutely! For each of the folder in `problems`, if you create a `problem_es.md` and `solution_es.md` which are translations of the english version, it should automatically use them :)

**Comment by manuelitox** [comment]
Thanks @SomeoneWeird 

I already did my first contribution :smiley:

**Comment by hquan** [comment]
Hi all, I'm new to here and want to make contributions.
Now I'm working on translating it to Chinese, hope it helpful.

A question is, how to tell the code to use solution_(zh-cn, ja, ko, etc.)? I tried `javascripting verify` but it always prints English solutions..

**Comment by sethvincent** [comment]
Cool! A Chinese translation is exciting.

When you run `javascripting` the first time there's a menu item at the bottom for choosing the language. Did you try that?

**Comment by hquan** [comment]
Yes I did try that. So the problem page was correctly printed out in Chinese, but the solution page was still in English.

Some thing in my configuration wrong?

**Comment by sethvincent** [comment]
I'm not sure. I just cloned your fork and tried verifying the introduction. It seems to work correctly for me.

Do you have javascripting installed via npm as well as the git repo for your fork? Maybe there's a mixup related to that?

**Comment by hquan** [comment]
Oh yes you are exactly correct. Now it works for me.

**Comment by sethvincent** [comment]
Cool!

**Comment by a0viedo** [comment]
Oh I forgot to update this, the spanish translations have been merged in https://github.com/sethvincent/javascripting/commit/2590853edcee60fee9ceafc740548bc9802ff0aa

**Comment by fmoliveira** [comment]
Hi everyone! It's so cool we have i18n suppport now!

I've started working on the Portuguese translation. I might finish it in a few days. :smiley:

**Comment by SomeoneWeird** [comment]
Awesome, go for it :)

**Comment by AlanCezarAraujo** [comment]
I've been working on translations and I finished 3 days ago.
Sorry I didn't told you guys.

Filipe, I'd be very happy to help on another NodeSchool translation.
Let me know if you want some hand.
:)

**Comment by fmoliveira** [comment]
No problem @AlanCezarAraujo , but next time you could share with us what you're working on to avoid duplicate work. Fortunately I had only 2 challenges translated, so, it was little effort.

That's great that you've finished it! I've done a quick review in some files and it looks good. I'll do a better review tonight and share my thoughts in the PR. :+1:

**Comment by SomeoneWeird** [comment]
@fmoliveira that would be great if you could review, i'll merge after you have a look :)

**Comment by fmoliveira** [comment]
Hi folks,

I've done the review. Sorry for being late. Details in #112.

**Comment by ipelekhan** [comment]
Hi everyone!

JFYI, I'm working on Russian translation of javascripting. Going to finish it in a week (procrastination go away :wink:).

**Comment by SomeoneWeird** [comment]
@ipelekhan awesome!

**Comment by ipelekhan** [comment]
Well, it took more than a week (procrastination never gone), but we've done it: https://github.com/sethvincent/javascripting/pull/160

@SomeoneWeird, could you or any other maintainers take a look, please?

**Comment by turquoisemelon** [comment]
Hi everyone! I've attended my first nodeschool workshop today in Toronto. Since I'm still learning the technical aspects of the things right now, I was wondering if I could contribute by making Turkish Translation of this material if it hasn't been done, yet.

Let me know what I can do :)

**Comment by sethvincent** [comment]
@turquoisemelon a Turkish translation would be great!

You can look at the existing translations to get a sense of what's required to add a new one: https://github.com/workshopper/javascripting/tree/master/i18n

Sidenote: I don't think we have a guide to contributing translations. If anyone wants to help with that, or knows where one exists for other similar workshoppers, that could be really useful.

**Comment by claudiopro** [comment]
@sethvincent I can set one up, I have some time tonight.

Hi @turquoisemelon, in the meantime you can have a look at my [Italian translation commit](https://github.com/workshopper/javascripting/commit/e3c79714de2203abfc226741f83ac09f30036291) to understand what's involved. Don't hesitate to ask if anything's not clear 😄

**Comment by turquoisemelon** [comment]
@sethvincent Thanks. Existing translations are definitely great sources. I'll try to make the Turkish one by taking them and @claudiopro's translation as a references. I'll also think of how to create such guide while going over my own translation. 

@claudiopro Great. Thanks for offering your help!

**Comment by claudiopro** [comment]
Hi @turquoisemelon, the localization guide [was added to the repo last night](https://github.com/workshopper/javascripting/blob/master/LOCALIZING.md), feel free to integrate. Hope it helps!

**Comment by turquoisemelon** [comment]
Hi @claudiopro , awesome! Thanks!

**Comment by ledsun** [comment]
I think the translation is complete
